version: 0.2

env:
  git-credential-helper: yes
        
phases:
  install:
    on-failure: CONTINUE
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Webhook Payload"
      - echo "${CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID}"
      - echo "${CODEBUILD_WEBHOOK_BASE_REF}"
      - echo "${CODEBUILD_WEBHOOK_EVENT}"
      - echo "${CODEBUILD_WEBHOOK_PREV_COMMIT}"
      - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
      - echo "${CODEBUILD_WEBHOOK_TRIGGER}"
    # steps:
  pre_build:
    on-failure: CONTINUE
    commands:
      - echo "pre_build"

    # steps:
  build:
    on-failure: CONTINUE
    commands:
      - echo "build"
  post_build:
    on-failure: CONTINUE
    commands:
      - echo "post_build"
